// Modified from https://github.com/skeletonlabs/skeleton/blob/main/eslint.config.js
import javascript from '@eslint/js';
import astro from 'eslint-plugin-astro';
import globals from 'globals';
import react from 'eslint-plugin-react';
import typescript from 'typescript-eslint';

/**
 * @see https://eslint.org/docs/latest/use/configure/
 * @type {import('eslint').Linter.Config}
 */
export default typescript.config(
  {
    ignores: [
      '**/node_modules/',
      '**/dist/',
      '**/build/',
      '**/pagefind/',
      '**/.svelte-kit/',
      '**/.astro/',
      '**/.next/',
      '**/.vercel/',
      // Local wrangler state, written by `pnpm preview` / `wrangler dev`.
      '**/.wrangler/',
      // Generated by `wrangler types`.
      'worker-configuration.d.ts'
    ]
  },
  // JavaScript
  javascript.configs.recommended,
  // TypeScript
  typescript.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off'
    }
  },
  // Node scripts — run under `node`, not in the browser or the Worker.
  {
    files: ['scripts/**/*.mjs', '*.config.{js,mjs}'],
    languageOptions: { globals: globals.nodeBuiltin }
  },
  // Astro
  astro.configs.recommended,
  {
    // Ambient namespace declared by `astro/astro-jsx`; used for typing component props.
    files: ['**/*.astro'],
    languageOptions: { globals: { astroHTML: 'readonly' } }
  },
  // React
  {
    files: ['**/*.tsx', '**/*.jsx'],
    ...react.configs.flat.recommended,
    ...react.configs.flat['jsx-runtime']
  }
);
